// <auto-generated />
using System;
using ES.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ES.DataAccess.Migrations
{
    [DbContext(typeof(DbContextAccess))]
    [Migration("20230704111449_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

<<<<<<< HEAD:ES.DataAccess/Migrations/EmployeeDbContextModelSnapshot.cs
            modelBuilder.Entity("ES.Model.LiftFunctionDetails", b =>
=======
            modelBuilder.Entity("ES.Model.Floor", b =>
>>>>>>> 33c0ca1307921d3a314abf3b8db162b7b4e707ce:ES.DataAccess/Migrations/20230704111449_Initial.Designer.cs
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

<<<<<<< HEAD:ES.DataAccess/Migrations/EmployeeDbContextModelSnapshot.cs
                    b.Property<int>("CurrentPostion")
                        .HasColumnType("int");

                    b.Property<bool>("EmergencyAlarm")
                        .HasColumnType("bit");

                    b.Property<bool>("Fan")
                        .HasColumnType("bit");

                    b.Property<bool>("FireAlarm")
                        .HasColumnType("bit");

                    b.Property<bool>("PowerStatus")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("LiftFunctionDetail");
=======
                    b.Property<int>("FloorNum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Floors");
>>>>>>> 33c0ca1307921d3a314abf3b8db162b7b4e707ce:ES.DataAccess/Migrations/20230704111449_Initial.Designer.cs
                });

            modelBuilder.Entity("ES.Model.PersonDetailsInLift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FromFloorNum")
                        .HasColumnType("int");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToFloorNum")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("PersonDetailsInLifts");
                });
#pragma warning restore 612, 618
        }
    }
}
